### PR TITLE
Removed all bluebird references

### LINKED ISSUE #8: Bluebird is unneeded
The bluebird dependency used within this package is unneeded in modern javascript engines. All I've tested recently include native promises.

### PR DESCRIPTION
**Pull request by finwo**
Fixes #8

### CODE REVIEW

**Comment by finwo** [comment]
@amark Have you had time to test this change yet?

**Comment by amark** [comment]
@finwo w00h00 👏 

We're doing a call tomorrow (Friday) 3pm CA time about PANIC, wanna join? See the #work thread on discord. Maybe save pulling this for then so others can see your contribution 👏  & inspire them !?

**Comment by finwo** [comment]
@amark Time for this one to be merged?

**Review by styfle — APPROVED** [review]

**Comment by amark** [comment]
Sorry, thanks for the reminder. I'm... impossibly scattered with so many tasks. Thank you for doing this one for me!!!! :D :)

**Pull request merged**
